"""empty message

Revision ID: 31c588e4ac24
Revises: 
Create Date: 2021-08-12 23:49:31.050332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c588e4ac24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divvy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('starttime', sa.Date(), nullable=True),
    sa.Column('stoptime', sa.Date(), nullable=True),
    sa.Column('bikeid', sa.Integer(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_name', sa.String(), nullable=True),
    sa.Column('usertype', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divvy')
    # ### end Alembic commands ###
